### ISSUE TITLE
Issue in Intro_to_r in loading arbuthnot.R

### ISSUE THREAD

**Issue by sunnyc7** [jbryer/DATA606#1]
The following command errors out in Lab0
`source("more/arbuthnot.R") 
`
The fix would be to reference the path with Lab0
`source("Lab0/more/arbuthnot.R")`

OS: Windows 10

**Comment by jbryer** [comment]
When knitting a Rmarkdown file R will look for files relative to where the Rmd file is located. When working interactively, you should change your working directory to where the Rmd file is. Note that the most recent version of RStudio should do this automatically. See slide 12 from the first meetup with a bit more about this: http://data606.net/slides/2018-01-31-Intro_to_Course.html#12
