### ISSUE TITLE
Package didn't install cleanly because of missing dependencies

### ISSUE THREAD

**Issue by mikeasilva** [jbryer/DATA606#3]
When installing the package, the install failed because of missing dependencies.  I installed them manually but think it may pose some difficulties for students who are not familiar with R.  I am happy to create a PR if you would like.

**Comment by jbryer** [comment]
Hi Michael. Which dependencies did you need to install? Did you install the
packages as listed on this page?
http://data606.net/course-overview/software/

**Comment by mikeasilva** [comment]
openintro and shiny weren't installed. They are imports in DATA606-package.r but not listed in the DESCRIPTION file.

**Comment by jbryer** [comment]
This has now been fixed.

**Comment by mikeasilva** [comment]
Thanks
