### ISSUE TITLE
Labs function not working

### ISSUE THREAD

**Issue by mikeasilva** [jbryer/DATA606#4]
Probably due to the fact that I'm on a Linux system but the file paths used by labs.R are not valid. The directories are lowercase.  Here's a screenshot of the package's directory:

![screenshot](https://user-images.githubusercontent.com/7127983/44581747-f5fb6500-a76c-11e8-921c-e9974e6785b7.png)

I have made some edits on my fork of your project.  Happy to make a PR.

**Comment by mikeasilva** [comment]
Just an amendment to this issue.  It seems it might be an R 3.5 as I am experiencing it on a Windows PC too running R 3.5.

**Comment by jbryer** [comment]
I fixed the DATA606 package. Try reinstalling the package with the
devtools::install_github('jbryer/DATA606') command.

For those still having an issue, you can download the labs directly from
this page using the "Template" link.
http://data606.net/assignments/labs/

**Comment by mikeasilva** [comment]
Reinstalled and that solved the issue.  Thanks.
